name: Scrape jobs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -e .

      - run: python -m src.main
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
